hostname p1-spine03
no service integrated-vtysh-config
!
password zebra
enable password zebra
!
ip nht resolve-via-default
ipv6 nht resolve-via-default
!
ipv6 route fc00:0001:20::/48 2001:db8:fab:0030::1
ipv6 route fc00:0001:21::/48 2001:db8:fab:0031::1
ipv6 route fc00:0001:22::/48 2001:db8:fab:0032::1
ipv6 route fc00:0001:23::/48 2001:db8:fab:0033::1
ipv6 route fc00:0001:24::/48 2001:db8:fab:0034::1
ipv6 route fc00:0001:25::/48 2001:db8:fab:0035::1
ipv6 route fc00:0001:26::/48 2001:db8:fab:0036::1
ipv6 route fc00:0001:27::/48 2001:db8:fab:0037::1
ipv6 route fc00:0001:28::/48 2001:db8:fab:0038::1
ipv6 route fc00:0001:29::/48 2001:db8:fab:0039::1
ipv6 route fc00:0001:2a::/48 2001:db8:fab:003a::1
ipv6 route fc00:0001:2b::/48 2001:db8:fab:003b::1
ipv6 route fc00:0001:2c::/48 2001:db8:fab:003c::1
ipv6 route fc00:0001:2d::/48 2001:db8:fab:003d::1
ipv6 route fc00:0001:2e::/48 2001:db8:fab:003e::1
ipv6 route fc00:0001:2f::/48 2001:db8:fab:003f::1
!
segment-routing
 srv6
  static-sids
   sid fc00:0001:13::/48 locator MAIN behavior uN
   sid fc00:0001:e000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:fab:0030::1
   sid fc00:0001:e001::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:fab:0031::1
   sid fc00:0001:e002::/48 locator MAIN behavior uA interface Ethernet8 nexthop 2001:db8:fab:0032::1
   sid fc00:0001:e003::/48 locator MAIN behavior uA interface Ethernet12 nexthop 2001:db8:fab:0033::1
   sid fc00:0001:e004::/48 locator MAIN behavior uA interface Ethernet16 nexthop 2001:db8:fab:0034::1
   sid fc00:0001:e005::/48 locator MAIN behavior uA interface Ethernet20 nexthop 2001:db8:fab:0035::1
   sid fc00:0001:e006::/48 locator MAIN behavior uA interface Ethernet24 nexthop 2001:db8:fab:0036::1
   sid fc00:0001:e007::/48 locator MAIN behavior uA interface Ethernet28 nexthop 2001:db8:fab:0037::1
   sid fc00:0001:e008::/48 locator MAIN behavior uA interface Ethernet32 nexthop 2001:db8:fab:0038::1
   sid fc00:0001:e009::/48 locator MAIN behavior uA interface Ethernet36 nexthop 2001:db8:fab:0039::1
   sid fc00:0001:e00a::/48 locator MAIN behavior uA interface Ethernet40 nexthop 2001:db8:fab:003a::1
   sid fc00:0001:e00b::/48 locator MAIN behavior uA interface Ethernet44 nexthop 2001:db8:fab:003b::1
   sid fc00:0001:e00c::/48 locator MAIN behavior uA interface Ethernet48 nexthop 2001:db8:fab:003c::1
   sid fc00:0001:e00d::/48 locator MAIN behavior uA interface Ethernet52 nexthop 2001:db8:fab:003d::1
   sid fc00:0001:e00e::/48 locator MAIN behavior uA interface Ethernet56 nexthop 2001:db8:fab:003e::1
   sid fc00:0001:e00f::/48 locator MAIN behavior uA interface Ethernet60 nexthop 2001:db8:fab:003f::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0001:13::1
  exit
  locators
   locator MAIN
    prefix fc00:0001:13::/48 block-len 32 node-len 16 func-bits 16
    behavior usid
   exit
   !
  exit
  !
  formats
   format usid-f3216
   exit
   !
   format uncompressed-f4024
   exit
   !
  exit
  !
 exit
!
exit
!
end
