hostname p0-spine02
no service integrated-vtysh-config
!
password zebra
enable password zebra
!
ip nht resolve-via-default
ipv6 nht resolve-via-default
!
ipv6 route fc00:0000:20::/48 2001:db8:fab:0020::1
ipv6 route fc00:0000:21::/48 2001:db8:fab:0021::1
ipv6 route fc00:0000:22::/48 2001:db8:fab:0022::1
ipv6 route fc00:0000:23::/48 2001:db8:fab:0023::1
ipv6 route fc00:0000:24::/48 2001:db8:fab:0024::1
ipv6 route fc00:0000:25::/48 2001:db8:fab:0025::1
ipv6 route fc00:0000:26::/48 2001:db8:fab:0026::1
ipv6 route fc00:0000:27::/48 2001:db8:fab:0027::1
ipv6 route fc00:0000:28::/48 2001:db8:fab:0028::1
ipv6 route fc00:0000:29::/48 2001:db8:fab:0029::1
ipv6 route fc00:0000:2a::/48 2001:db8:fab:002a::1
ipv6 route fc00:0000:2b::/48 2001:db8:fab:002b::1
ipv6 route fc00:0000:2c::/48 2001:db8:fab:002c::1
ipv6 route fc00:0000:2d::/48 2001:db8:fab:002d::1
ipv6 route fc00:0000:2e::/48 2001:db8:fab:002e::1
ipv6 route fc00:0000:2f::/48 2001:db8:fab:002f::1
!
segment-routing
 srv6
  static-sids
   sid fc00:0000:12::/48 locator MAIN behavior uN
   sid fc00:0000:e000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:fab:0020::1
   sid fc00:0000:e001::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:fab:0021::1
   sid fc00:0000:e002::/48 locator MAIN behavior uA interface Ethernet8 nexthop 2001:db8:fab:0022::1
   sid fc00:0000:e003::/48 locator MAIN behavior uA interface Ethernet12 nexthop 2001:db8:fab:0023::1
   sid fc00:0000:e004::/48 locator MAIN behavior uA interface Ethernet16 nexthop 2001:db8:fab:0024::1
   sid fc00:0000:e005::/48 locator MAIN behavior uA interface Ethernet20 nexthop 2001:db8:fab:0025::1
   sid fc00:0000:e006::/48 locator MAIN behavior uA interface Ethernet24 nexthop 2001:db8:fab:0026::1
   sid fc00:0000:e007::/48 locator MAIN behavior uA interface Ethernet28 nexthop 2001:db8:fab:0027::1
   sid fc00:0000:e008::/48 locator MAIN behavior uA interface Ethernet32 nexthop 2001:db8:fab:0028::1
   sid fc00:0000:e009::/48 locator MAIN behavior uA interface Ethernet36 nexthop 2001:db8:fab:0029::1
   sid fc00:0000:e00a::/48 locator MAIN behavior uA interface Ethernet40 nexthop 2001:db8:fab:002a::1
   sid fc00:0000:e00b::/48 locator MAIN behavior uA interface Ethernet44 nexthop 2001:db8:fab:002b::1
   sid fc00:0000:e00c::/48 locator MAIN behavior uA interface Ethernet48 nexthop 2001:db8:fab:002c::1
   sid fc00:0000:e00d::/48 locator MAIN behavior uA interface Ethernet52 nexthop 2001:db8:fab:002d::1
   sid fc00:0000:e00e::/48 locator MAIN behavior uA interface Ethernet56 nexthop 2001:db8:fab:002e::1
   sid fc00:0000:e00f::/48 locator MAIN behavior uA interface Ethernet60 nexthop 2001:db8:fab:002f::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0000:12::1
  exit
  locators
   locator MAIN
    prefix fc00:0000:12::/48 block-len 32 node-len 16 func-bits 16
    behavior usid
   exit
   !
  exit
  !
  formats
   format usid-f3216
   exit
   !
   format uncompressed-f4024
   exit
   !
  exit
  !
 exit
!
exit
!
end
