hostname p3-spine06
no service integrated-vtysh-config
!
password zebra
enable password zebra
!
ip nht resolve-via-default
ipv6 nht resolve-via-default
!
ipv6 route fc00:0003:20::/48 2001:db8:fab:0060::1
ipv6 route fc00:0003:21::/48 2001:db8:fab:0061::1
ipv6 route fc00:0003:22::/48 2001:db8:fab:0062::1
ipv6 route fc00:0003:23::/48 2001:db8:fab:0063::1
ipv6 route fc00:0003:24::/48 2001:db8:fab:0064::1
ipv6 route fc00:0003:25::/48 2001:db8:fab:0065::1
ipv6 route fc00:0003:26::/48 2001:db8:fab:0066::1
ipv6 route fc00:0003:27::/48 2001:db8:fab:0067::1
ipv6 route fc00:0003:28::/48 2001:db8:fab:0068::1
ipv6 route fc00:0003:29::/48 2001:db8:fab:0069::1
ipv6 route fc00:0003:2a::/48 2001:db8:fab:006a::1
ipv6 route fc00:0003:2b::/48 2001:db8:fab:006b::1
ipv6 route fc00:0003:2c::/48 2001:db8:fab:006c::1
ipv6 route fc00:0003:2d::/48 2001:db8:fab:006d::1
ipv6 route fc00:0003:2e::/48 2001:db8:fab:006e::1
ipv6 route fc00:0003:2f::/48 2001:db8:fab:006f::1
!
segment-routing
 srv6
  static-sids
   sid fc00:0003:16::/48 locator MAIN behavior uN
   sid fc00:0003:e000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:fab:0060::1
   sid fc00:0003:e001::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:fab:0061::1
   sid fc00:0003:e002::/48 locator MAIN behavior uA interface Ethernet8 nexthop 2001:db8:fab:0062::1
   sid fc00:0003:e003::/48 locator MAIN behavior uA interface Ethernet12 nexthop 2001:db8:fab:0063::1
   sid fc00:0003:e004::/48 locator MAIN behavior uA interface Ethernet16 nexthop 2001:db8:fab:0064::1
   sid fc00:0003:e005::/48 locator MAIN behavior uA interface Ethernet20 nexthop 2001:db8:fab:0065::1
   sid fc00:0003:e006::/48 locator MAIN behavior uA interface Ethernet24 nexthop 2001:db8:fab:0066::1
   sid fc00:0003:e007::/48 locator MAIN behavior uA interface Ethernet28 nexthop 2001:db8:fab:0067::1
   sid fc00:0003:e008::/48 locator MAIN behavior uA interface Ethernet32 nexthop 2001:db8:fab:0068::1
   sid fc00:0003:e009::/48 locator MAIN behavior uA interface Ethernet36 nexthop 2001:db8:fab:0069::1
   sid fc00:0003:e00a::/48 locator MAIN behavior uA interface Ethernet40 nexthop 2001:db8:fab:006a::1
   sid fc00:0003:e00b::/48 locator MAIN behavior uA interface Ethernet44 nexthop 2001:db8:fab:006b::1
   sid fc00:0003:e00c::/48 locator MAIN behavior uA interface Ethernet48 nexthop 2001:db8:fab:006c::1
   sid fc00:0003:e00d::/48 locator MAIN behavior uA interface Ethernet52 nexthop 2001:db8:fab:006d::1
   sid fc00:0003:e00e::/48 locator MAIN behavior uA interface Ethernet56 nexthop 2001:db8:fab:006e::1
   sid fc00:0003:e00f::/48 locator MAIN behavior uA interface Ethernet60 nexthop 2001:db8:fab:006f::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0003:16::1
  exit
  locators
   locator MAIN
    prefix fc00:0003:16::/48 block-len 32 node-len 16 func-bits 16
    behavior usid
   exit
   !
  exit
  !
  formats
   format usid-f3216
   exit
   !
   format uncompressed-f4024
   exit
   !
  exit
  !
 exit
!
exit
!
end
